from __future__ import annotations

import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional


class StockStrategyId(str, Enum):
    MEAN_REVERSION = "mean_reversion"
    TREND_FOLLOWING = "trend_following"
    BREAKOUT = "breakout"
    VOLUME_SPIKE = "volume_spike"
    DIVERGENCE = "divergence"
    RSI_REVERSAL = "rsi_reversal"


@dataclass(frozen=True)
class CandleBar:
    timestamp: float
    open: float
    high: float
    low: float
    close: float
    volume: float


@dataclass(frozen=True)
class StockQuote:
    ticker: str
    bid: float
    ask: float
    last: float
    volume: float
    timestamp: float = field(default_factory=time.time)


@dataclass(frozen=True)
class StockSnapshot:
    """Complete market state for a single ticker at a point in time."""
    ticker: str
    quote: StockQuote
    candles: List[CandleBar]
    portfolio_value: float
    cash_available: float
    current_position_qty: int
    indicators: Dict[str, float]
    lot_size: int = 1                   # MOEX lot size (shares per lot)
    timestamp: float = field(default_factory=time.time)


@dataclass(frozen=True)
class StockTradeIntent:
    """Signal generated by a strategy — single-leg order proposal."""
    strategy_id: StockStrategyId
    ticker: str
    side: str                           # "buy" | "sell"
    quantity_lots: int
    order_type: str = "market"          # "market" | "limit"
    limit_price: Optional[float] = None
    confidence: float = 0.0
    expected_edge_pct: float = 0.0
    stop_loss_pct: float = 3.0
    take_profit_pct: float = 4.5
    mode: str = "auto"                  # "auto" | "semi_auto"
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class StockPosition:
    """An open stock position tracked by the system."""
    position_id: str
    strategy_id: StockStrategyId
    ticker: str
    side: str
    quantity_lots: int
    entry_price: float
    stop_loss_price: float
    take_profit_price: float
    opened_at: float = field(default_factory=time.time)
    realized_pnl: float = 0.0
    peak_price: float = 0.0  # highest (buy) / lowest (sell) price seen — for trailing stop
    trailing_stop_pct: float = 0.0  # 0 = disabled; >0 = trail SL by this % from peak
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class StockExecutionReport:
    success: bool
    position_id: Optional[str] = None
    fill_price: float = 0.0
    quantity_lots: int = 0
    commission: float = 0.0
    message: str = ""


@dataclass
class StockRiskDecision:
    approved: bool
    reason: str
    kill_switch_triggered: bool = False
